apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "votingApp.fullname" . }}-{{ include "votingApp.configVersion" . }}
  labels:
    {{- include "votingApp.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
data:
{{- range $key, $value := .Values.votingApp.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
