---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "votingApp.fullname" . }}-{{ include "votingApp.secretVersion" . }}
  labels:
    {{- include "votingApp.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
type: Opaque
data:
{{- range $key, $value := .Values.votingApp.secrets }}
  {{ $key }}: {{ b64enc $value }}
{{- end }}
