{{- if .Values.votingApp.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "votingApp.fullname" . }}
  labels:
    {{- include "votingApp.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: NodePort
  ports:
    - port: {{ .Values.votingApp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "votingApp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
